// store.js
import { configureStore, createSlice } from "@reduxjs/toolkit";

// Create a slice of the state, automatically generating actions
const menuSlice = createSlice({
  name: "menu",
  initialState: {
    menuOpen: false,
  },
  reducers: {
    toggleMenu: (state) => {
      state.menuOpen = !state.menuOpen;
    },
    // You can add more reducers here if you have other actions
  },
});

// Export the action generated by the slice
export const { toggleMenu } = menuSlice.actions;

// Create a Redux store with the slice reducer
const store = configureStore({
  reducer: {
    menu: menuSlice.reducer,
  },
});

export default store;
